
\thispagestyle{empty}
\vfill
\center

# Abstract {.unnumbered .unlisted}

\flushleft
\vspace{0.5cm}

This paper examines the electoral responses to wind turbine development at the polling-precinct level using retrospective voting behaviour and party expectations as the theoretical framework.

In a natural experiment I use register data on wind turbine development and precinct-level election results at municipal elections in the years 2009 until 2021. I find no direct correlation between wind turbine construction and electoral support for the mayoral party. Looking across parties, I find that right-wing mayors are more likely to be penalised for wind turbine construction, while left-wing mayors are electorally rewarded.

This project contributes to the growing litterature on electoral responses to wind turbine development and climate policy in general and sheds ligth on how right- and left-wing mayoral parties receive different electoral responses. I build upon findings by @stokes2016, Larsen, Uhre and Lægreid [-@larsen2021], and Isaksson and Gren [-@isaksson2024a] while drawing parralles to distributional policy as proposed by Aklin and Mildenberger [-@aklin2020]. I conclude that right-wing mayors are more likely to be punished for wind turbine development, while left-wing mayors are more likely to be rewarded for the same. This has clear implications for which local politicians are able to allow wind turbine development without being electorally punished.

\vfill\vfill
