---
# project:
#   title: "Bacheloropgave"
author: "Aleksander Bang-Larsen"
bibliography: ../../../Andet/Zotero/zotero.bib
csl: csl/politica-w-ibid.csl
format:
  pdf:
    link-citations: true
    colorlinks: false
toc: true
numbersections: true
language: custom-lang-da.yml
