---
project:
  # title: "Bacheloropgave"
  output-dir: "output"
author: "Aleksander Bang-Larsen"
date: "07-06-2024"
lang: "da"
date-format: "D. MMMM YYYY"
bibliography: ../../../Andet/Zotero/zotero.bib
csl: csl/politica-w-ibid.csl
format:
  pdf:
    link-citations: true
    colorlinks: false
toc: false
lot: false
lof: false
numbersections: true
language: custom-lang-da.yml
