---
project:
  title: "Bacheloropgave"
author: "Aleksander Bang-Larsen"
bibliography: ../../../Andet/Zotero/zotero.bib
csl: csl/politica-w-ibid.csl
format:
  pdf:
    link-citations: true
    colorlinks: false
