---
# project:
#   title: "Bacheloropgave"
author: "Aleksander Bang-Larsen"
date: "07-06-2024"
bibliography: ../../../Andet/Zotero/zotero.bib
csl: csl/politica-w-ibid.csl
format:
  pdf:
    link-citations: true
    colorlinks: false
toc: false
lot: false
lof: false
numbersections: true
language: custom-lang-da.yml
