---
project:
  title: Bachelorprojekt
  output-dir: output
  preview:
    port: 4200
author:
  - name: Aleksander Bang-Larsen
    affiliation: Aarhus Universitet
subtitle: |
  | Vælgernes reaktion på opførelsen af vindmøller og solcelleanlæg i lokalområdet - Og hvordan man kan forbedre accepten
  |
  |
  |
  | 166F24 Vælgeradfærd og politisk repræsentation
  | Vejleder: Martin Bisgaard
date: 07-06-2024
lang: da
date-format: D. MMMM YYYY
mainfont: Arial
bibliography: ../../../Andet/Zotero/zotero.bib
csl: csl/politica-w-ibid.csl

numbersections: true
language: format/custom-lang-da.yml

# Forside
# abstract: |
#   Det her er et bachelorprojekt om vælgeradfærd og politisk repræsentation.
#   Projektet undersøger, hvordan vælgere opfatter politisk repræsentation
#   og hvilken betydning det har for deres valg. Projektet er baseret på en
#   spørgeskemaundersøgelse, som er gennemført i forbindelse med valget til
#   Folketinget i 2023. Resultaterne viser, at vælgere har en bred forståelse
#   af politisk repræsentation

# Output style
format:
  pdf:
    latex-auto-install: true
    # include-after-body: format/tex/after-body.tex
    # include-before-body: format/tex/before-body.tex
    # include-in-header: format/tex/header.tex
    # template-partials:
    #   - "format/tex/before-body.tex"
    #   - "format/tex/_titlepage.tex"
    link-citations: true
    colorlinks: false
    keep-tex: false
    # documentclass: article
    toc: true
    lot: true
    lof: true
    geometry:
      - top=2cm
      - bottom=4cm
      - left=2cm
      - right=2cm
      - heightrounded
    linestretch: 1.5
    papersize: a4
    mermaid:
      theme: forest
