---
project:
  title: Bachelorprojekt
  output-dir: output
  preview:
    port: 4200
# author:
#   - name: Aleksander Bang-Larsen
#     affiliation: Aarhus Universitet
title: Forventninger, klimapolitik og retrospektiv stemmeadfærd
subtitle: Vælgernes elektorale reaktion på vindmøller i lokalområdet
date: 07-06-2024
lang: da
date-format: D. MMMM YYYY
# mainfont: "{{< var font >}}"
# sansfont: "{{< var font >}}"
# mathfont: "{{< var font >}}"

fontsize: "{{< var fontsize >}}"
bibliography: ../../../Andet/Zotero/zotero.bib
csl: csl/politica-w-ibid.csl

execute:
  echo: false
  warning: false
  error: false
  output: false

engine: knitr

author: ""

cap-location: top

numbersections: true
language: format/custom-lang-da.yml

# # Forside
# abstract: |
#   Det her er et bachelorprojekt om vælgeradfærd og politisk repræsentation.
#   Projektet undersøger, hvordan vælgere opfatter politisk repræsentation
#   og hvilken betydning det har for deres valg. Projektet er baseret på en
#   spørgeskemaundersøgelse, som er gennemført i forbindelse med valget til
#   Folketinget i 2023. Resultaterne viser, at vælgere har en bred forståelse
#   af politisk repræsentation


# Output style
format:
  pdf:
    fig-pos: "H"
    latex-auto-install: true
    # include-after-body: format/tex/after-body.tex
    include-in-header:
      - file: format/tex/pagenumbers.tex
      - file: format/tex/in-header.tex
    link-citations: true
    colorlinks: false
    keep-tex: true
    # documentclass: article
    # documentclass: scrreprt
    template-partials:
      - "format/tex/before-body.tex"
      - "format/tex/_titlepage.tex"
    lof: false
    lot: false
    toc: false
    geometry:
      - top=2cm
      - bottom=4cm
      - left=2cm
      - right=2cm
      - heightrounded
    linestretch: 1.5
    papersize: a4
    # fig-width: 10
    # fig-height: 10
    mermaid:
      theme: forest
      fontFamily: "{{< var font >}}"
      fontSize: "{{< var mermaid_fontsize >}}"
    quarto-required: 1.4.555   # Er produceret med denne version af Quarto
