---
title: "Bachelor ide"
format:
  revealjs:
    # theme: simple
    slide-number: true
    citations-hover: false
    mermaid:
      theme: forest
  # pptx:
  #   incremental: false
suppress-bibliography: true
date: 04-02-2024
---

## Spørgsmål

Hvordan reagerer vælgerne på policybeslutninger med "diffuse benefits and concentrated local costs"

- Det bedste eksempel er vindmøller og solcelleanlæg (og dæmninger til vandkraft, men de er ikke udbredt i DK)

- Særlig relevant for klimaspørgsmål
- Ændres effekten hvis lokalsamfundet får medarbejerskab?

##

### Den simple model

```{mermaid}
flowchart LR
  A(Opførelse af vedvarende energianlæg) --> B(Ændring i elektoral tilslutning)
```

### Den lokalt betingede model

```{mermaid}
flowchart LR
  %% A(Opførelse af vedvarende energianlæg) --> B(Ændring i elektoral tilslutning)

  C(Lokalt ejerskab over anlæg)
  D(Negativ elektoral effekt for siddende politikere)
  E(Ingen eller lille positiv elektoral effekt for siddende politikere)

  C -->|Ja| D
  C -->|Nej| E
```

## Design

???

## Andre studier

- @stokes2016
  - Undersøger vindmøller i Ontario
- @larsen2021
  - Ikke endnu udgivet
  - Undersøger vindmøller i Danmark (ligesom L. Stokes)

## Forventninger

Jeg regner med at finde samme resultater som @larsen2021 og @stokes2016 for de anlæg der ikke har lokal ejerskab

Andel med lokal indflydelse og ejerskab forventes at have mindre, hvis nogen overhovedet, effekt.

## Forslag fra holdtimen

Støtte til parti i stedet for borgmesteren
- Ændring i støtte til miljøpartier
- Ændring i støtte til miljøskeptiske partier

<!-- ## Litteratur

:::{#refs}
::: -->
