---
title: "Synopsis"
date: "5 april 2024"
subtitle: ""
abstract: ""
format:
  pdf:
    toc: false
    lof: false
    lot: false
---

# Motivation

For at forsøge at løse klimakrisen er det essentielt de folkevalgte kan implementere klimatiltag med påvirkning på borgerne uden at blive synderligt elektoralt straffet for det - I hvert fald, hvis borgerne grundlæggende ønsker at klimakrisen skal løses.

# Overordnet spørgsmål

I min bachelor vil jeg gerne undersøge spørgsmålet:

> Hvordan reagerer vælgere på klimatiltag med koncentrerede omkostninger og diffuse samfundsmæssige fordele?

Her ser jeg det specifikt interessant at undersøge, hvordan opførslen af vindmøller (og/eller solcelleparker) i området tæt på vælgeren påvirker dennes støtte til de siddende beslutningstagere.

## Hvorfor vindmøller?

Jeg vurderer at vindmøller kan udgøre et godt eksempel på en klimapolicy som vælgerne, generelt, går ind for at udbygge, men er udsat for den såkaldte NIMBY effekt [@lex.dk2016]. NIMBY står for "Not in my backyard" og beskriver meget godt, hvad jeg ser som det største argument, fra borgerne, for, hvorfor der ikke skal opføres vindmøller i den enkeltes lokalområde.

Jeg ser NIMBY effekten som en reaktion på de koncentrerede omkostninger der er ved klimatiltag som vindmøller, hvor der er nogle borgere der får opsat store metalmonstre tæt på hjemmet, som både bryder med landskabet og kan udgøre en støjgene, hvis man er tæt nok på.

Denne effekt kan tænkes at være til stede hos vælgerne for både vindmøller, solcelleparker og anlæg til produktion af vandkraft. Jeg vurderer dog at vindmøller er den de tre, der skaber den største gene. Samtidig er der ikke nok nævneværdige vandkraftsanlæg opført i Danmark til at disse bør med i betragtnignen.

# Teori

Grundlaget for at undersøge mit spørgsmål bygger på flere teoretiske perspektiver. Her vil jeg tage udgangspunkt i @stokes2016, @ogrady2020 og @brouwer2024.

@ogrady2020 [3] finder at "price anxiety" er med til at drive negative holdninger til opførslen af billige boliger i lokalområder. Den samme price anxiety vurderer jeg kan have en lignende, om end ikke lige så stærk, påvirkning på holdningen til opførslen af vindmøller i lokalområdet. For begge scenarier er der tale om udbyggelse af boligens omegn, hvor billige boliger øger udbuddet vil vindmøller mindske efterspørgslen på grund af de gener der er forbundet med det.

@hankinson2018 [6] har en rigtig god definition og forklaring på NIMBY som jeg abonnerer på. Han definerer NIMBY-adfærd som individer der på makro skala er enig med et tiltag, mens denne støtte ikke følger med til mikro-niveauet [@hankinson2018]. Det kan i kontekst af opførslen af vindmøller ses som støtte til generel opførsel af vindmøller, men ikke støtte til at de skal bygges i lige ens eget lokalområde.
Et billede der passer på denne beskrivelse kan findes i Danmark, hvor der er generel tilslutning til opførslen af vindmøller, men ofte opstår lokale debatter om, hvor de skal placeres [@videnomvind2022;@nielsen2021].

Den forventede sammenhæng er illustreret i @fig-kausalmodel-simpel og @fig-kausalmodel-fuld

```{mermaid}
%%| label: fig-kausalmodel-simpel
%%| fig-cap: "Forventet simpel sammenhæng"

flowchart LR
  X(Vindmølle sættes op)
  Y(Borgmesterparti mindsker tilslutning)
  Y2(Borgmesterparti ser ingen ændring i tilslutning)
  Ja
  Nej

  X --> Ja --> Y
  X --> Nej --> Y2

  style X fill-opacity:0, stroke-opacity:0
  style Y fill-opacity:0, stroke-opacity:0
  style Y2 fill-opacity:0, stroke-opacity:0
  style Ja fill-opacity:0, stroke-opacity:0
  style Nej fill-opacity:0, stroke-opacity:0
```


## Lignende studier

@stokes2016

# Metode

## Data

Der findes opgørelser over alle vindmøller [@energistyrelsen2024], hvor det er muligt at se både møllens tilslutningsdato (og evt. afmeldingsdato), møllens kapacitet og størrelse, samt data om placering. Placeringsdata findes med koordinater der virker ret præcise.

Sammenholdt med data over opsættelse af vindmøllerne vil jeg bruge valgdata til kommunalvalg på valgstedsniveau over tid. Her vælger jeg kommunalvalgsdata fordi det er på det kommunale niveau der besluttes lokalplaner der kan begrænse/tillade vindmøllerne.

Med disse to kilder sammenholdt vil jeg kunne skabe et nyt dataset med de variable jeg er interesseret i til min analyse.

## Design

- [ ] Her skal stå noget om hvilke modeller der kan laves og hvordan jeg vil gå til det

# Forventninger

Jeg forventer i stil med @stokes2016 at der ved opførslen af en vindmølle indenfor valgstedets geografiske område mellem valg vil give en nedgang i tilslutningen til borgmesterens parti i kommunen. Leah Stokes finder en nedgang på -10 procentpoint [@stokes2016: 966], hvor jeg vil forvente, bl.a. på baggrund af @larsen2021, at nedgangen er er til stede, men mindre i Danmark.

{{< pagebreak >}}

<!-- # Appendiks {.appendix}

I @fig-kausalmodel-fuld ses den kausalmodel jeg forventer at se når borgerne får indflydelse på projekterne.
```{mermaid}
%%| label: fig-kausalmodel-fuld
%%| fig-cap: "Forventet fuld sammenhæng"

flowchart TD
  X(Vindmølle sættes op)
  Y(Borgmesterparti mindsker tilslutning)
  Y2(Borgmesterparti ser ingen ændring i tilslutning)

  Z(Indflydelse på projekt)

  X --> Z
  Z --> Ja --> Y
  Z --> Nej --> Y2

  style X fill-opacity:0, stroke-opacity:0
  style Y fill-opacity:0, stroke-opacity:0
  style Y2 fill-opacity:0, stroke-opacity:0
  style Z fill-opacity:0, stroke-opacity:0
  style Ja fill-opacity:0, stroke-opacity:0
  style Nej fill-opacity:0, stroke-opacity:0

```


{{< pagebreak >}} -->

# Bibliografi

::: {#refs}
:::
