<!-- \lipsum[1-2] -->

```{r}
#| label: tbl-appendix-a-borgmester-regres
#| tbl-cap: Fuld regressionstabel for borgmesterpartier
#| output: true
msummary(appendix_a_modeller, stars = sign_stjerner, output = "gt", gof_omit = "AIC|BIC", gof_map = tbl_borgmester_interaktion_modeller_gof_map, notes = list("Klyngerobuste standardfejl og fixed effects for valgsted og valg", "Referencekategorien er Socialdemokratiet. SF, Alternativet og DF udeladt af model 3."), coef_rename = TRUE) %>%
  tab_spanner(label = "Afhængig: Stemmeandel til borgmesterparti i %", columns = -1)
```

{{< pagebreak >}}

```{r}
#| label: tbl-appendix-a-uden
#| tbl-cap: Regressionstabel for borgmesterpartier uden kommuner, hvor borgmesterparti ikke er genopstillet.
#| output: true
msummary(appendix_a_modeller_uden, stars = sign_stjerner, output = "gt", gof_omit = "AIC|BIC", gof_map = tbl_borgmester_interaktion_modeller_gof_map, notes = list("Klyngerobuste standardfejl og fixed effects for valgsted og valg", "Referencekategorien er Socialdemokratiet. SF, Alternativet og DF udeladt af model 3."), coef_rename = TRUE) %>%
  tab_spanner(label = "Afhængig: Stemmeandel til borgmesterparti i %", columns = -1)
```
